version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: ${NGINX_HOST}
        volumes:
            - "./www/:/var/www/html"
            - "./storage/logs/nginx:/var/www/log/"
            - "./etc/php-fpm/php.ini:/etc/php/7.1/fpm/php.ini"
            - "./etc/php-fpm/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf"
            - "./etc/nginx/${NGINX_CONFIG}.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/nginx.conf/:/etc/nginx/nginx.conf/"
            - "./etc/ssh:/root/.ssh"
            - "./etc/git:/root/"
        ports:
            - "80:80"
        depends_on:
            - db-mysql
            - memcached
            - redis
            - rabbitmq
            - elasticsearch

    db-mysql:
        container_name: mysql-${NGINX_HOST}
        image: mysql:5.7
        volumes:
          - ./mysql/default.cnf:/etc/mysql/conf.d/default.cnf:ro
          - ./storage/data/db/mysql:/var/lib/mysql
          - ./storage/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "3306:3306"

    memcached:
        container_name: memcached-${NGINX_HOST}
        image: memcached:1.4

    redis:
      container_name: redis-${NGINX_HOST}
      image: redis:3.2
      restart: always
      volumes:
        - ./storage/data/db/redis:/data
      ports:
        - 6379:6379


    rabbitmq:
      container_name: rabbitmq-${NGINX_HOST}
      image: rabbitmq

    elasticsearch:
      container_name: elasticsearch-${NGINX_HOST}
      image: elasticsearch:2.4.6
    #  command: elasticsearch -Des.network.host=0.0.0.0
      ports:
        - "9200:9200"